### ISSUE TITLE
除了README.md文件，没看到其他文件

### ISSUE THREAD

**Issue by lin2415016** [WuDi-ZhanShen/PvZ-TV-Touch#2]

**Comment by WuDi-ZhanShen** [comment]
看release

**Comment by stephen-cusi** [comment]
在release的zip里面
（

**Comment by lin2415016** [comment]
谢谢，看到了
        
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月17日 20:42
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [WuDi-ZhanShen/PvZ-TV-Touch] 除了README.md文件，没看到其他文件 (Issue #2)
        
      
    
  

在release的zip里面
（

**Comment by lin2415016** [comment]
谢谢，看到了
        
    
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月17日 16:40
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [WuDi-ZhanShen/PvZ-TV-Touch] 除了README.md文件，没看到其他文件 (Issue #2)
        
      
    
  

看release
